CREATE TABLE IF NOT EXISTS tokens_revogados (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token VARCHAR(512) NOT NULL UNIQUE,
  revogado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  criado_em TIMESTAMP NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMP NOT NULL DEFAULT NOW()
);
